### ISSUE TITLE
Allow for deployment of Sites to LiteSpeed Servers

### ISSUE THREAD

**Issue by jordantrizz** [StouteWebSolutions/whmcs-gridpane#3]
Leaving this as a placeholder. Will need to have LiteSpeed specific options.

**Comment by pstoute** [comment]
I'm not sure there's an issue on this. The API doesn't offer anything related to LiteSpeed... yet.

**Comment by jordantrizz** [comment]
100% so you can close this or add it as a feature request when it's available via the API.

**Comment by pstoute** [comment]
I'll close this out for now. We're reviewing the API documentation for changes on a weekly basis right now, so we'll catch the Lightspeed options when they show up.
