### ISSUE TITLE
Server Blank

### ISSUE THREAD

**Issue by Veeau** [StouteWebSolutions/whmcs-gridpane#4]
Hello thanks for this!

I may have likely missed something during the setup but on the order and in the product the server is blank.

![Image 2](https://user-images.githubusercontent.com/44915545/114131398-22bc1500-9935-11eb-9907-93c935ef2ec5.jpg)
![Image 3](https://user-images.githubusercontent.com/44915545/114131402-251e6f00-9935-11eb-8e1f-39fc5a82e04d.jpg)

**Comment by Mindsix** [comment]
I was testing the module and it doesn't work. I wondered if the problem was also related to the server that does not appear in the dropdown menu. I don't see how to debug.

@pstoute Do you still maintain this module?

**Comment by Veeau** [comment]
@Mindsix I cannot get it to work at all either. It doesnt seem to interact with GP at all, which makes me think I am doing something wrong in the setup.

**Comment by Veeau** [comment]
@pstoute Are you able to help here so we can start testing?

**Comment by pstoute** [comment]
@Veeau I've been on vacation and out of the office since the 1st of May. I'm back now and will look into this, this week.

**Comment by Veeau** [comment]
@pstoute  thanks!

**Comment by vincentjanv** [comment]
Yeah, keen on getting some more documentation as well.

Setup the API key, and then added a server under 'Servers'. I gave it the same name as in Gridpane, but it seems the API (and the module) are expecting an INT value (server ID). The only way to retrieve those at the moment is to look into the API calls on the Gridpane control panel. But then it's still unclear where to add them. Will see if I can do a pull request with some improvements.

**Comment by pstoute** [comment]
@vincentjanv @Veeau Please look at the updated instructions on this project. I'll be working on a way that we can remove the need for the custom field, but for now that's what we have available.
